### ISSUE TITLE
cbft crashes on indexes that have all bucket documents indexed

### ISSUE THREAD

**Issue by abhi-bit** [couchbaselabs/cbft#168] opened 2015-08-06 17:06 UTC
Background about scenario:

```
cbft version: 0.2.0(released on 19-Jun)
bucket document count: under 10K
kvstore: leveldb
```

Fired a query for the word "centos"/"windows" against the index that was upto date and then cbft crashed.

error-log: http://s3.amazonaws.com/customers.couchbase.com/couchbase/cbft-panic

**Comment by mschoch** [comment] 2015-08-06 17:10
It looks like the panic is in the highlighter.  This would be consistent with known issues (at the time) if the field containing the match was an array.  Can you share a sample document?

**Comment by abhi-bit** [comment] 2015-08-06 17:16
Sample documents are shared on https://github.com/couchbaselabs/cbft/issues/165

**Comment by mschoch** [comment] 2015-08-06 18:41
I have reproduced the problem when I checked out the old version of Bleve (2768c2d) corresponding to the 0.2 cbft release.  Running the same query with the latest code does not crash.

**Comment by steveyen** [comment] 2015-12-11 22:27
closing this since we're on latest bleve now

**Closed by steveyen** 2015-12-11 22:27 UTC
