### ISSUE TITLE
MB-16121: If a source bucket is not found, cbft throws authentication error instead

### ISSUE THREAD

**Issue by arunapiravi** [couchbaselabs/cbft#175] opened 2015-08-20 00:38 UTC
https://issues.couchbase.com/browse/MB-16121

**Comment by steveyen** [comment] 2016-01-22 17:43
Taking a look again at this after a long hiatus, the issue is REST call to couchbase isn't giving any info that the source bucket isn't there, but just that there's an auth error, so cbft can't tell the distinction.

Closing this, then, as can't fix.

**Closed by steveyen** 2016-01-22 17:43 UTC
